name: ticket
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  fluentui_icons: ^1.0.0
  get: ^4.6.6
  path_provider: ^2.1.3
  google_fonts: ^6.2.1
  syncfusion_flutter_calendar: ^26.1.41
  awesome_dialog: ^3.2.1
  awesome_icons: ^1.1.0
  intl: ^0.19.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  firebase_database: ^11.0.3
  shared_preferences: ^2.2.3
  animated_text_kit: ^4.2.2
  provider: ^6.1.2
  http: ^1.2.1
  flutter_spinkit: ^5.2.1
  fl_chart: ^0.68.0
  flutter_advanced_drawer: ^1.3.6
  intl_phone_number_field: ^0.2.0
  iconly: ^1.0.1
  font_awesome_flutter: ^10.7.0
  auto_size_text: ^3.0.0
  ionicons: ^0.2.2
  anim_search_bar: ^2.0.3
  file_picker: ^8.0.6
  fluttertoast: ^8.2.6
  uuid: ^4.4.2
  twilio_flutter: ^0.9.0
  go_router: ^14.2.1
  qr_flutter: ^4.1.0
  pdf: ^3.11.0
  printing: ^5.13.1
  open_file: ^3.3.2
  flutter_barcode_scanner: ^2.0.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/pngs/logo-icon.png"

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/pngs/
    - assets/icons/
    - assets/fonts/